### ISSUE TITLE
pcache-gae: users should be able to operate in specific namespace

### ISSUE THREAD

**Issue by qnislavnachev** [clouway/clouway-pcache-client#1]
When users using ``` pcache-gae ```, it's good they should be able to operate in different namespaces.

**Comment by qnislavnachev** [comment]
@mgenov what do you think about this change ?

**Comment by mgenov** [comment]
The namespace of the MemcacheService depends on the namespace that is set by the NamespaceManager which should be controlled by the app.

**Comment by qnislavnachev** [comment]
This sound it's the right option.
